# Generated by Django 3.0.8 on 2020-07-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.AddField(
            model_name='about',
            name='des',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
