# Generated by Django 3.0.8 on 2020-07-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200710_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(upload_to='projects/templates/pics'),
        ),
    ]
